import React from 'react';
import { BillItem } from '../types/Bill';
import './Receipt.css';

interface ReceiptProps {
  items: BillItem[];
  subtotal: number;
  tax: number;
  total: number;
  customerPhone: string;
}

const Receipt: React.FC<ReceiptProps> = ({ 
  items, 
  subtotal, 
  tax, 
  total, 
  customerPhone 
}) => {
  return (
    <div className="receipt">
      <div className="receipt-header">
        {/* Logo Section in Receipt */}
        <div className="receipt-logo">
          <div className="receipt-logo-image">
            <div className="receipt-logo-placeholder">
              <span>Dev.Marcel</span>
            </div>
          </div>
          <div className="receipt-watermark">Marcellas Did It</div>
        </div>
        
        <h2>=== MATEVA ===</h2>
        <p>Thank you for shopping!</p>
      </div>
      
      <div className="receipt-items">
        {items.map((item) => (
          <div key={item.id} className="receipt-item">
            <div className="item-main">
              <span className="item-name">{item.name}</span>
              <span className="item-quantity">x{item.quantity}</span>
            </div>
            <div className="item-price">
              ${(item.quantity * item.price).toFixed(2)}
            </div>
          </div>
        ))}
      </div>
      
      <div className="receipt-totals">
        <div className="total-line">
          <span>Subtotal:</span>
          <span>${subtotal.toFixed(2)}</span>
        </div>
        <div className="total-line">
          <span>Tax:</span>
          <span>${tax.toFixed(2)}</span>
        </div>
        <div className="total-line grand-total">
          <span>TOTAL:</span>
          <span>${total.toFixed(2)}</span>
        </div>
      </div>
      
      <div className="receipt-footer">
        <p>Customer: {customerPhone}</p>
        <p>Date: {new Date().toLocaleString()}</p>
        <div className="receipt-signature">
          <p>Generated by Marcellas</p>
        </div>
      </div>
    </div>
  );
};

export default Receipt;